# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ed2b52e68e45dd1268f3757c22150010815f83055d9fee9cffeb19acc27db8a8644fc28060bda51ab7aa37ddcd5ee0ca38c09b45f0f38b4b7b65b448e593ca4

test:
  secret_key_base: ff11ceafde3ae5a50d4b449edc39363ae38870c1be13805508e715b93c2e1e01667fd352a1a0de2086b03207fa9dc30d5aeb5e2132d5c62d30342bf86072d54e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
